version : '3.4'
services:
  swagger:
    build:
      context: ..
      dockerfile: germes-web/src/main/resources/docker/swagger.dockerfile
    ports:
      - "8000:8080"
    environment:
      - SWAGGER_JSON=/opt/swagger.json   
