version : '3.4'
services:
  graphite:
    image: graphiteapp/graphite-statsd
    restart: always
    networks:
      - network1
    ports:
      - "80:80"          
      - "2003-2004:2003-2004"          
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"      
  grafana:
    image: grafana/grafana
    networks:
      - network1    
    ports:
      - "3000:3000"
  admin:
    environment:               
      - graphite.reporter.enabled=true
    