version: '3.7'
services:

  ubuntu-20.04:
    privileged: true
    container_name: bash2container
    build:
      context: .
      dockerfile: ./Dockerfile
    network_mode: host
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "/home/skorpion/1.Soft/0.Projects/1.MyProjects/info/info/another/1.courses/1.yodo/1.bash/2.nginx-php-fm/src:/home/root"
