
# В этом примере, если сервер вернет код ответа 200, задача будет успешно выполнена1.
#  Если сервер не вернет код ответа 200 в течение 5 минут (30 попыток с интервалом в 10 секунд),
#  задача завершится с ошибкой1.
- name: Проверить, что вы можете подключиться (GET) к странице и она возвращает статус 200
  uri:
    url: http://www.example.com
    method: GET
    status_code: 200
    return_content: yes
    validate_certs: no
  register: result
  until: result.status == 200
  retries: 30
  delay: 10