version: '3.7'
services:

  ubuntu-20.04:
    privileged: true
    container_name: bash2container
    build:
      context: .
      dockerfile: ./Dockerfile
    network_mode: host
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "${TOP}/3.nginx-php-fm-backup/src:/home/root"
#      - "${TOP}/3.nginx-php-fm-backup/src:/home/root/.bashrc"
#      - "${TOP}/3.nginx-php-fm-backup/crontab:/var/spool/cron/crontabs/root"
