---
- name: create file1
  copy:
    dest: /home/secret/file1.txt
    content: |
      Text Line1, in file1
      Text Line2, in file1
      Text Line3, {{mytext}}

- name: create file2
  copy:
    dest: /home/secret/file2.txt
    content: |
      Text Line1, in file1
      Text Line2, in file1
      Text Line3, {{mytext}}