---
# vars file for springboot-service-deploy
sysd_user_services_folder: "{{ '/etc/systemd/system' if (ansible_distribution in ['RedHat','CentOS']) else '/etc/systemd/system/' }}"
sysd_script: "{{ sysd_user_services_folder }}/{{ service_name | lower }}.service"
