galaxy_info:
  author: carlosramillan94
  description: springboot services deploy
  company: your company (optional)

  license: license BSD-3-Clause

  min_ansible_version: 2.1

  platforms:
  - name: Ubuntu
    versions:
      - all

  galaxy_tags:
    - java
    - systemd
    - springboot
